SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `ARTICLE`;
CREATE TABLE IF NOT EXISTS `ARTICLE` (
  `ArticleID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(1000) DEFAULT NULL,
  `Pages` varchar(45) DEFAULT NULL,
  `VolumeID` int(11) NOT NULL,
  PRIMARY KEY (`ArticleID`),
  KEY `VolumeID_idx` (`VolumeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ARTICLE_AUTHOR`;
CREATE TABLE IF NOT EXISTS `ARTICLE_AUTHOR` (
  `ArticleID` int(11) NOT NULL AUTO_INCREMENT,
  `AuthorID` int(11) NOT NULL,
  PRIMARY KEY (`ArticleID`,`AuthorID`),
  KEY `AuthorID_idx` (`AuthorID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `CID` int(11) NOT NULL AUTO_INCREMENT,
  `fname` varchar(45) DEFAULT NULL,
  `lname` varchar(45) DEFAULT NULL,
  `address` varchar(45) DEFAULT NULL,
  `phone` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `DAY`;
CREATE TABLE IF NOT EXISTS `DAY` (
  `D_Year` int(11) NOT NULL,
  `D_Month` int(11) NOT NULL,
  `D_Day` int(11) NOT NULL,
  PRIMARY KEY (`D_Day`),
  KEY `D_Year` (`D_Year`),
  KEY `D_Month` (`D_Month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `SIN` int(11) NOT NULL,
  PRIMARY KEY (`SIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `MONTH`;
CREATE TABLE IF NOT EXISTS `MONTH` (
  `Year` int(11) NOT NULL,
  `Month` int(11) NOT NULL,
  `Electicity` float DEFAULT NULL,
  `Heat` float DEFAULT NULL,
  `Water` float DEFAULT NULL,
  PRIMARY KEY (`Month`),
  KEY `Year_idx` (`Year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TRANSACTION`;
CREATE TABLE IF NOT EXISTS `TRANSACTION` (
  `TID` int(11) NOT NULL AUTO_INCREMENT,
  `CID` int(11) NOT NULL,
  `discountcode` varchar(45) DEFAULT NULL,
  `tdate` date DEFAULT NULL,
  `totalprice` float DEFAULT NULL,
  PRIMARY KEY (`TID`),
  KEY `CID_idx` (`CID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TRANSACTIONDETAILS`;
CREATE TABLE IF NOT EXISTS `TRANSACTIONDETAILS` (
  `TID` int(11) NOT NULL,
  `itemID` bigint(20) DEFAULT NULL,
  KEY `TID_idx` (`TID`),
  KEY `IID_idx` (`itemID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `VOLUME`;
CREATE TABLE IF NOT EXISTS `VOLUME` (
  `MagazineID` int(11) NOT NULL,
  `VolumeID` int(11) NOT NULL AUTO_INCREMENT,
  `Year` int(11) NOT NULL,
  `volumeNo` varchar(30) NOT NULL,
  PRIMARY KEY (`VolumeID`),
  KEY `_id_idx` (`MagazineID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `WORK`;
CREATE TABLE IF NOT EXISTS `WORK` (
  `SIN` int(11) NOT NULL,
  `W_Year` int(11) DEFAULT NULL,
  `W_Month` int(11) DEFAULT NULL,
  `W_Day` int(11) DEFAULT NULL,
  `Hours` int(11) DEFAULT NULL,
  PRIMARY KEY (`SIN`),
  KEY `W_Year_idx` (`W_Year`),
  KEY `W_Month_idx` (`W_Month`),
  KEY `W_Day_idx` (`W_Day`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `YEAR`;
CREATE TABLE IF NOT EXISTS `YEAR` (
  `Year` int(11) NOT NULL,
  `MonthlyRent` float DEFAULT NULL,
  PRIMARY KEY (`Year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ARTICLE`
  ADD CONSTRAINT `VolumeID` FOREIGN KEY (`VolumeID`) REFERENCES `VOLUME` (`VolumeID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `ARTICLE_AUTHOR`
  ADD CONSTRAINT `ArticleID` FOREIGN KEY (`ArticleID`) REFERENCES `ARTICLE` (`ArticleID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `AuthorID` FOREIGN KEY (`AuthorID`) REFERENCES `AUTHOR` (`_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `DAY`
  ADD CONSTRAINT `D_Month` FOREIGN KEY (`D_Month`) REFERENCES `MONTH` (`Month`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `D_Year` FOREIGN KEY (`D_Year`) REFERENCES `MONTH` (`Year`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `MONTH`
  ADD CONSTRAINT `Year` FOREIGN KEY (`Year`) REFERENCES `YEAR` (`Year`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `TRANSACTION`
  ADD CONSTRAINT `CID` FOREIGN KEY (`CID`) REFERENCES `CUSTOMER` (`CID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `TRANSACTIONDETAILS`
  ADD CONSTRAINT `IID` FOREIGN KEY (`itemID`) REFERENCES `ITEM` (`_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `TID` FOREIGN KEY (`TID`) REFERENCES `TRANSACTION` (`TID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `VOLUME`
  ADD CONSTRAINT `MagazineID` FOREIGN KEY (`MagazineID`) REFERENCES `MAGAZINE` (`_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `WORK`
  ADD CONSTRAINT `SIN` FOREIGN KEY (`SIN`) REFERENCES `EMPLOYEE` (`SIN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `W_Day` FOREIGN KEY (`W_Day`) REFERENCES `DAY` (`D_Day`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `W_Month` FOREIGN KEY (`W_Month`) REFERENCES `DAY` (`D_Month`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `W_Year` FOREIGN KEY (`W_Year`) REFERENCES `DAY` (`D_Year`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;


